(setq org-tag-alist `(
                      ("humeur" .?h)
                      ("actu" .?a)
                      ("@lire" .?l)
                      ("@voir" .?v)
                      ("prospective" .?p)
                      ("@noter" .?n)
                      ))
(setq org-capture-templates
      '(
        ("e" "Improve my emacs" entry (file+headline "~/ownCloud/org/todo.org" "Emacs")
         "** TODO %?\n  %i\n  %a")
        ("f" "Famille (todo)" entry (file+headline "~/ownCloud/org/todo.org" "Famille")
         "** TODO %?\n  %i\n  %a")
        ("m" "Maison (todo" entry (file+headline "~/ownCloud/org/todo.org" "Maison")
         "** TODO %?\n  %i\n  %a")
        ("l" "Labo (todo)" entry (file+headline "~/ownCloud/org/todo.org" "Labo")
         "** TODO %?\n  %i\n  %a")
        ("t" "Enseignement (todo)" entry (file+headline "~/ownCloud/org/todo.org" "Teaching")
         "** TODO %?\n  %i\n  %a")
        ("b" "Labbook" entry (file+datetree "~/ownCloud/Documents/Labbook/labnotes.org")
         "* %?\nEntered on %U\n  %i\n  %a")
        ("j" "journal" entry (file+datetree "~/ownCloud/org/journal.org")
         "* %^G %?\n Entered on %U \n  %i\n  %a")
        )
      )

